# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0007_thread_last_post'),
        ('categories', '0002_auto_20171021_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='latest_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latest_thread', to='threads.Thread'),
        ),
    ]
