# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_latest_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
