# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_auto_20171020_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='initial_post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='initial_post', to='threads.Post'),
        ),
    ]
