# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('threads', '0003_auto_20171020_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
            preserve_default=False,
        ),
    ]
