# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_thread_date_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='message',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=froala_editor.fields.FroalaField(default='this is cool'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thread',
            name='pin_status',
            field=models.CharField(choices=[('Not pinned', 'none'), ('Locally pinned for category', 'locally'), ('Globally pinned for category', 'globally')], default='Not pinned', max_length=50),
        ),
    ]
