# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0006_auto_20171021_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='last_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_post', to='threads.Post'),
        ),
    ]
