# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0008_auto_20171022_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='date_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
