# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_category_description'),
        ('threads', '0009_auto_20171022_2107'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together=set([('title', 'category')]),
        ),
    ]
