# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0010_auto_20171025_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
