# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0011_auto_20171028_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='last_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_post', to='threads.Post'),
        ),
    ]
