# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0012_auto_20171112_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='initial_post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_post', to='threads.Post'),
        ),
    ]
