# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, help_text='Add a sassy description for your profile', max_length=150, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=500, upload_to='C:\\Users\\Alex\\Dropbox\\De Tortelduifjes\\Alex\\Alex- School 4de jaar\\iframe\\iframe\\src\\public/media\\uploads/display_pictures'),
        ),
    ]
