# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171025_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
