# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171106_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=500, upload_to='display_pictures'),
        ),
    ]
